# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be107085834a870ffde1f9f6bdafaa5db7c93a32638379b415389c9ef682f9cf02832f7b5f06ff5a0e35cbdafe7a2a74c7cabab42f10284caaf131bd58704e0e

test:
  secret_key_base: 48be7ba09295145295016b059e462caec8debb2fe0e20a6e41411fa15fc73df2c3896af581c37c511414ce25a629e7bfc9efc196f4ce7a4edeeec9fe29d4a473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
